name: APP Test

on:
  pull_request:
    branches:
      - main

env:
  yarn-version: 3.6.1

jobs:
  app-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn

      - name: setup yarn@3.x
        run: yarn set version ${{ env.yarn-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "DIR_PATH=~/.yarn/cache" >> $GITHUB_OUTPUT

      - name: cache yarn-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.DIR_PATH }}
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-cache-

      - name: install
        run: yarn install

      - name: show dir
        run: ls

      - name: show absolute path
        run: ls ~

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: fmt
        run: yarn fmt
